<?php
require_once('ClassActor.php');

$player1 = new Actor();
$player1->setTeam('player');
$player1->setStyle('ranger');
$player2 = new Actor();
$player2->setTeam('player');
$player2->setStyle('archer');
$player3 = new Actor();
$player3->setTeam('player');
$player3->setStyle('gunner');
$player4 = new Actor();
$player4->setTeam('player');
$player4->setStyle('cannoneer');
$player5 = new Actor();
$player5->setTeam('player');
$player5->setStyle('mechknight');
$player6 = new Actor();
$player6->setTeam('player');
$player6->setStyle('thief');
$player7 = new Actor();
$player7->setTeam('player');
$player7->setStyle('blackbelt');
$player8 = new Actor();
$player8->setTeam('player');
$player8->setStyle('samurai');
$player9 = new Actor();
$player9->setTeam('player');
$player9->setStyle('assassin');
$player10 = new Actor();
$player10->setTeam('player');
$player10->setStyle('ninja');
$player11 = new Actor();
$player11->setTeam('player');
$player11->setStyle('bard');
$player12 = new Actor();
$player12->setTeam('player');
$player12->setStyle('dancer');
$player13 = new Actor();
$player13->setTeam('player');
$player13->setStyle('chemist');
$player14 = new Actor();
$player14->setTeam('player');
$player14->setStyle('beastmaster');
$player15 = new Actor();
$player15->setTeam('player');
$player15->setStyle('minstrel');
$player16 = new Actor();
$player16->setTeam('player');
$player16->setStyle('warrior');
$player17 = new Actor();
$player17->setTeam('player');
$player17->setStyle('knight');
$player18 = new Actor();
$player18->setTeam('player');
$player18->setStyle('paladin');
$player19 = new Actor();
$player19->setTeam('player');
$player19->setStyle('sentinel');
$player20 = new Actor();
$player20->setTeam('player');
$player20->setStyle('berserker');
$player21 = new Actor();
$player21->setTeam('player');
$player21->setStyle('mage');
$player22 = new Actor();
$player22->setTeam('player');
$player22->setStyle('blackmage');
$player23 = new Actor();
$player23->setTeam('player');
$player23->setStyle('necromancer');
$player24 = new Actor();
$player24->setTeam('player');
$player24->setStyle('whitemage');
$player25 = new Actor();
$player25->setTeam('player');
$player25->setStyle('sage');

//echo "<img src='test_arrow_.png' width='128' height='128'/>";

echo $player1->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player2->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player3->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player4->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $player5->getImg();
echo "<br><br><br><br>";

echo $player6->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player7->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player8->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $player9->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player10->getImg();
echo "<br><br><br><br>";

echo $player11->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player12->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player13->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $player14->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $player15->getImg();
echo "<br><br><br><br>";

echo $player16->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player17->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player18->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $player19->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $player20->getImg();
echo "<br><br><br><br>";

echo $player21->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player22->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player23->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $player24->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $player25->getImg();
echo "<br><br><br><br>";





$enemy1 = new Actor();
$enemy1->setTeam('enemy');
$enemy1->setStyle('ranger');
$enemy2 = new Actor();
$enemy2->setTeam('enemy');
$enemy2->setStyle('archer');
$enemy3 = new Actor();
$enemy3->setTeam('enemy');
$enemy3->setStyle('gunner');
$enemy4 = new Actor();
$enemy4->setTeam('enemy');
$enemy4->setStyle('cannoneer');
$enemy5 = new Actor();
$enemy5->setTeam('enemy');
$enemy5->setStyle('mechknight');
$enemy6 = new Actor();
$enemy6->setTeam('enemy');
$enemy6->setStyle('thief');
$enemy7 = new Actor();
$enemy7->setTeam('enemy');
$enemy7->setStyle('blackbelt');
$enemy8 = new Actor();
$enemy8->setTeam('enemy');
$enemy8->setStyle('samurai');
$enemy9 = new Actor();
$enemy9->setTeam('enemy');
$enemy9->setStyle('assassin');
$enemy10 = new Actor();
$enemy10->setTeam('enemy');
$enemy10->setStyle('ninja');
$enemy11 = new Actor();
$enemy11->setTeam('enemy');
$enemy11->setStyle('bard');
$enemy12 = new Actor();
$enemy12->setTeam('enemy');
$enemy12->setStyle('dancer');
$enemy13 = new Actor();
$enemy13->setTeam('enemy');
$enemy13->setStyle('chemist');
$enemy14 = new Actor();
$enemy14->setTeam('enemy');
$enemy14->setStyle('beastmaster');
$enemy15 = new Actor();
$enemy15->setTeam('enemy');
$enemy15->setStyle('minstrel');
$enemy16 = new Actor();
$enemy16->setTeam('enemy');
$enemy16->setStyle('warrior');
$enemy17 = new Actor();
$enemy17->setTeam('enemy');
$enemy17->setStyle('knight');
$enemy18 = new Actor();
$enemy18->setTeam('enemy');
$enemy18->setStyle('paladin');
$enemy19 = new Actor();
$enemy19->setTeam('enemy');
$enemy19->setStyle('sentinel');
$enemy20 = new Actor();
$enemy20->setTeam('enemy');
$enemy20->setStyle('berserker');
$enemy21 = new Actor();
$enemy21->setTeam('enemy');
$enemy21->setStyle('mage');
$enemy22 = new Actor();
$enemy22->setTeam('enemy');
$enemy22->setStyle('blackmage');
$enemy23 = new Actor();
$enemy23->setTeam('enemy');
$enemy23->setStyle('necromancer');
$enemy24 = new Actor();
$enemy24->setTeam('enemy');
$enemy24->setStyle('whitemage');
$enemy25 = new Actor();
$enemy25->setTeam('enemy');
$enemy25->setStyle('sage');

//echo "<img src='test_arrow_.png' width='128' height='128'/>";

echo $enemy1->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy2->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy3->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy4->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $enemy5->getImg();
echo "<br><br><br><br>";

echo $enemy6->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy7->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy8->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $enemy9->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy10->getImg();
echo "<br><br><br><br>";

echo $enemy11->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy12->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy13->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $enemy14->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $enemy15->getImg();
echo "<br><br><br><br>";

echo $enemy16->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy17->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy18->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $enemy19->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $enemy20->getImg();
echo "<br><br><br><br>";

echo $enemy21->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy22->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy23->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $enemy24->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $enemy25->getImg();
echo "<br><br><br><br>";





$neutral1 = new Actor();
$neutral1->setTeam('neutral');
$neutral1->setStyle('ranger');
$neutral2 = new Actor();
$neutral2->setTeam('neutral');
$neutral2->setStyle('archer');
$neutral3 = new Actor();
$neutral3->setTeam('neutral');
$neutral3->setStyle('gunner');
$neutral4 = new Actor();
$neutral4->setTeam('neutral');
$neutral4->setStyle('cannoneer');
$neutral5 = new Actor();
$neutral5->setTeam('neutral');
$neutral5->setStyle('mechknight');
$neutral6 = new Actor();
$neutral6->setTeam('neutral');
$neutral6->setStyle('thief');
$neutral7 = new Actor();
$neutral7->setTeam('neutral');
$neutral7->setStyle('blackbelt');
$neutral8 = new Actor();
$neutral8->setTeam('neutral');
$neutral8->setStyle('samurai');
$neutral9 = new Actor();
$neutral9->setTeam('neutral');
$neutral9->setStyle('assassin');
$neutral10 = new Actor();
$neutral10->setTeam('neutral');
$neutral10->setStyle('ninja');
$neutral11 = new Actor();
$neutral11->setTeam('neutral');
$neutral11->setStyle('bard');
$neutral12 = new Actor();
$neutral12->setTeam('neutral');
$neutral12->setStyle('dancer');
$neutral13 = new Actor();
$neutral13->setTeam('neutral');
$neutral13->setStyle('chemist');
$neutral14 = new Actor();
$neutral14->setTeam('neutral');
$neutral14->setStyle('beastmaster');
$neutral15 = new Actor();
$neutral15->setTeam('neutral');
$neutral15->setStyle('minstrel');
$neutral16 = new Actor();
$neutral16->setTeam('neutral');
$neutral16->setStyle('warrior');
$neutral17 = new Actor();
$neutral17->setTeam('neutral');
$neutral17->setStyle('knight');
$neutral18 = new Actor();
$neutral18->setTeam('neutral');
$neutral18->setStyle('paladin');
$neutral19 = new Actor();
$neutral19->setTeam('neutral');
$neutral19->setStyle('sentinel');
$neutral20 = new Actor();
$neutral20->setTeam('neutral');
$neutral20->setStyle('berserker');
$neutral21 = new Actor();
$neutral21->setTeam('neutral');
$neutral21->setStyle('mage');
$neutral22 = new Actor();
$neutral22->setTeam('neutral');
$neutral22->setStyle('blackmage');
$neutral23 = new Actor();
$neutral23->setTeam('neutral');
$neutral23->setStyle('necromancer');
$neutral24 = new Actor();
$neutral24->setTeam('neutral');
$neutral24->setStyle('whitemage');
$neutral25 = new Actor();
$neutral25->setTeam('neutral');
$neutral25->setStyle('sage');

//echo "<img src='test_arrow_.png' width='128' height='128'/>";

echo $neutral1->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral2->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral3->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral4->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $neutral5->getImg();
echo "<br><br><br><br>";

echo $neutral6->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral7->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral8->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $neutral9->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral10->getImg();
echo "<br><br><br><br>";

echo $neutral11->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral12->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral13->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $neutral14->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $neutral15->getImg();
echo "<br><br><br><br>";

echo $neutral16->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral17->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral18->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $neutral19->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $neutral20->getImg();
echo "<br><br><br><br>";

echo $neutral21->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral22->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral23->getImg();
echo "<br>";
echo "<img src='empty.png' width='128' height='128'/>";
echo "<img src='test_arrow_down_right.png' width='128' height='128'/>";
echo $neutral24->getImg();
echo "<img src='test_arrow_right.png' width='128' height='128'/>";
echo $neutral25->getImg();
echo "<br><br><br><br>";